matrix:
  include:
    - stage: "Lint"
      language: node_js
      os: linux
      node_js: "12"
      script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "WebPack and Build"
      os: osx
      env:
        - WebPack="iOS"
      osx_image: xcode12.3
      language: node_js 
      node_js: "12"
      jdk: oraclejdk8
      before_install: pip install six
      script: cd demo && npm run build.plugin && npm i && tns build ios --env.uglify
    - language: android
      os: linux
      env:
        - WebPack="Android"
      jdk: oraclejdk8
      before_install: nvm install 12
      script: cd demo && npm run build.plugin && npm i && tns build android --env.uglify
    - stage: "Tests"
      os: linux
      language: android
      dist: trusty
      sudo: required
      jdk: oraclejdk8
      before_script:
        - android list targets
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install 12
      script: cd src && npm i && npm run build && npm run test.android
    # - os: osx
    #   language: node_js
    #   node_js: "12"
    #   jdk: oraclejdk8
    #   osx_image: xcode12.3
    #   before_install:
    #     - pip install six
    #   before_script:
    #     - export IOS_SIMULATOR_UDID=$(xcrun xctrace list devices 2>&1 | grep "(13.5)" | grep -i "iphone" | sed -E 's/.*\(([0-9A-F-]+)\).*/\1/g' | head -n1)
    #     - xcrun simctl list
    #     - xcrun simctl boot $IOS_SIMULATOR_UDID
    #     - sleep 120
    #     - xcrun simctl list | grep "(Booted)"
    #   script: cd src && npm i && npm run build && travis_retry npm run test.ios

android:
  components:
    - tools
    - platform-tools
    - build-tools-28.0.3
    - android-28
    - android-21
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21
  licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

install:
  - echo no | npm install -g nativescript
  - tns usage-reporting disable
  - tns error-reporting disable